version: "3"
services:
  db:
    restart: always
    image: "postgres:10.2"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
